import { Router, type IRouter } from "express";
import healthRouter from "./health";
import studyaiRouter from "./studyai";
import chatRouter from "./chat";
import simuladoRouter from "./simulado";
import flashcardsRouter from "./flashcards";
import historyRouter from "./history";
import rankingRouter from "./ranking";
import waitlistRouter from "./waitlist";
import streakRouter from "./streak";
import redacaoRouter from "./redacao";
import analyticsRouter from "./analytics";
import simuladoAdaptativoRouter from "./simulado-adaptativo";
import resumaoRouter from "./resumao";
import subscriptionRouter from "./subscription";
import feedRouter from "./feed";
import adminRouter from "./admin";
import professorRouter from "./professor";
import lgpdRouter from "./lgpd";
import profileRouter from "./profile";
import leadsRouter from "./leads";
import teacherContentRouter from "./teacherContent";
import teacherRouter from "./teacher";
import institutionRouter from "./institution";
import governmentRouter from "./government";
import knowledgeRouter from "./knowledge";
import wikipediaRouter from "./wikipedia";
import bnccRouter from "./bncc";
import simuladoEnemRouter from "./simulado-enem";
import ocrRouter from "./ocr";
import notifyRouter from "./notify";
import salaEstudosRouter from "./sala-estudos";
import flashcardReviewsRouter from "./flashcard-reviews";
import studentRouter from "./student";
import aulaIaRouter from "./aula-ia";
import trilhaRouter from "./trilha";
import notebookRouter from "./notebook";
import geminiRouter from "./gemini";
import openaiImageRouter from "./openai-image";
import studioIaRouter from "./studio-ia";
import comunicacaoRouter from "./comunicacao";
import contentHistoryRouter from "./content-history";
import boardRouter from "./board";
import aiCacheChatRouter from "./ai-cache-chat";
import fazedoresRouter from "./fazedores";
import scholarRouter from "./scholar";
import bnccCurriculumRouter from "./bncc-curriculum";
import enemBankRouter from "./enem-bank";
import concursosRouter from "./concursos";
import ragMultiRouter from "./rag-multi";
import mathRouter from "./math";
import inlineSearchRouter from "./inline-search";
import videosRouter from "./videos";

const router: IRouter = Router();

router.use(healthRouter);
router.use(studyaiRouter);
router.use(chatRouter);
router.use(simuladoRouter);
router.use(flashcardsRouter);
router.use(historyRouter);
router.use(rankingRouter);
router.use(waitlistRouter);
router.use(streakRouter);
router.use(redacaoRouter);
router.use(analyticsRouter);
router.use(simuladoAdaptativoRouter);
router.use(resumaoRouter);
router.use(subscriptionRouter);
router.use(feedRouter);
router.use(adminRouter);
router.use(professorRouter);
router.use(lgpdRouter);
router.use(profileRouter);
router.use(leadsRouter);
router.use(teacherContentRouter);
router.use(teacherRouter);
router.use(institutionRouter);
router.use(governmentRouter);
router.use(knowledgeRouter);
router.use(wikipediaRouter);
// BNCC — A1 follow-up: paths canônicos vivem em `/api/bncc/*` (montagem do
// `bnccCurriculumRouter` mais abaixo). O router legado fica preservado em
// `/api/bncc/legacy/*` apenas para compat de consumidores antigos; emite
// console.warn a cada hit.
router.use("/bncc/legacy", bnccRouter);
router.use(simuladoEnemRouter);
router.use(ocrRouter);
router.use(notifyRouter);
router.use(salaEstudosRouter);
router.use(flashcardReviewsRouter);
router.use(studentRouter);
router.use(aulaIaRouter);
router.use(trilhaRouter);
router.use(notebookRouter);
router.use(geminiRouter);
router.use(openaiImageRouter);
router.use(studioIaRouter);
router.use(boardRouter);
router.use(contentHistoryRouter);
router.use(comunicacaoRouter);
router.use(aiCacheChatRouter);
router.use(fazedoresRouter);
router.use(scholarRouter);
// BNCC — A1 follow-up: rotas canônicas em /api/bncc/{areas,competencias,align}.
router.use("/bncc", bnccCurriculumRouter);
router.use(enemBankRouter);
router.use(concursosRouter);
router.use(ragMultiRouter);
router.use(mathRouter);
router.use(inlineSearchRouter);
router.use(videosRouter);

export default router;
