import { Router, type IRouter } from "express";
import healthRouter from "./health";
import studyaiRouter from "./studyai";
import chatRouter from "./chat";
import simuladoRouter from "./simulado";
import flashcardsRouter from "./flashcards";
import historyRouter from "./history";
import rankingRouter from "./ranking";
import waitlistRouter from "./waitlist";
import streakRouter from "./streak";
import redacaoRouter from "./redacao";
import analyticsRouter from "./analytics";
import simuladoAdaptativoRouter from "./simulado-adaptativo";
import resumaoRouter from "./resumao";
import subscriptionRouter from "./subscription";
import feedRouter from "./feed";
import adminRouter from "./admin";
import professorRouter from "./professor";
import lgpdRouter from "./lgpd";
import profileRouter from "./profile";
import leadsRouter from "./leads";
import teacherContentRouter from "./teacherContent";
import teacherRouter from "./teacher";
import institutionRouter from "./institution";
import governmentRouter from "./government";
import knowledgeRouter from "./knowledge";
import wikipediaRouter from "./wikipedia";
import bnccRouter from "./bncc";
import simuladoEnemRouter from "./simulado-enem";
import ocrRouter from "./ocr";
import notifyRouter from "./notify";
import salaEstudosRouter from "./sala-estudos";
import flashcardReviewsRouter from "./flashcard-reviews";
import studentRouter from "./student";
import aulaIaRouter from "./aula-ia";
import trilhaRouter from "./trilha";

const router: IRouter = Router();

router.use(healthRouter);
router.use(studyaiRouter);
router.use(chatRouter);
router.use(simuladoRouter);
router.use(flashcardsRouter);
router.use(historyRouter);
router.use(rankingRouter);
router.use(waitlistRouter);
router.use(streakRouter);
router.use(redacaoRouter);
router.use(analyticsRouter);
router.use(simuladoAdaptativoRouter);
router.use(resumaoRouter);
router.use(subscriptionRouter);
router.use(feedRouter);
router.use(adminRouter);
router.use(professorRouter);
router.use(lgpdRouter);
router.use(profileRouter);
router.use(leadsRouter);
router.use(teacherContentRouter);
router.use(teacherRouter);
router.use(institutionRouter);
router.use(governmentRouter);
router.use(knowledgeRouter);
router.use(wikipediaRouter);
router.use(bnccRouter);
router.use(simuladoEnemRouter);
router.use(ocrRouter);
router.use(notifyRouter);
router.use(salaEstudosRouter);
router.use(flashcardReviewsRouter);
router.use(studentRouter);
router.use(aulaIaRouter);
router.use(trilhaRouter);

export default router;
