// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aula-professor/BibleProject.tsx": () => import("../components/mockups/aula-professor/BibleProject.tsx"),
  "./components/mockups/aula-professor/EstiloAtual.tsx": () => import("../components/mockups/aula-professor/EstiloAtual.tsx")
};
